project:
  type: book
license: CC BY-SA
latex-auto-install: true

lang: fr
language:
  toc-title-document: "Table des matières"
  title-block-author-plural: "Auteurs"
  repo-action-links-issue: "Signaler un problème ou<br>formuler une suggestion"
crossref:
  lof-title: "Liste des figures"
  lot-title: "Listes des tableaux"
  fig-prefix: figure
  tbl-prefix: tableau
  sec-prefix: section
  eq-prefix: équation
  fig-title: Figure
  tbl-title: Tableau
  eq-title: Équation
book:
  title: "Visualisation interactive de données dans R avec animint2"
  repo-url: https://github.com/animint/animint-manual-fr
  repo-actions: [edit, issue, source]
  repo-subdir: chapitres
  favicon: Figures/favicon.ico
  cover-image: Figures/logo.png
  downloads: [pdf]
  sidebar:
    style: "docked"
    collapse-level: 2
    border: true
    search: true
  page-footer:
    left: |
      All content licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) <br> &copy; [Toby Dylan Hocking](https://tdhock.github.io).
    center: "[GitHub](https://github.com/animint/animint2) | [Galerie](https://animint.github.io/gallery-fr)"
    right: Built with [Quarto](https://quarto.org/).
    background: "#f8f9fa"
  chapters:
    - index.qmd
    - part: "Fonctions de base"
      chapters:
      - ch02/index.qmd
      - ch03/index.qmd
      - ch04/index.qmd
      - ch05/index.qmd
      - ch06/index.qmd
      - ch07/index.qmd
    - part: "Exemples avancés"
      chapters:
      - ch08/index.qmd
      - ch09/index.qmd
      - ch10/index.qmd
      - ch11/index.qmd
      - ch12/index.qmd
      - ch13/index.qmd
      - ch14/index.qmd
      - ch15/index.qmd
      - ch16/index.qmd
      - ch17/index.qmd
      - ch18/index.qmd
      - ch19/index.qmd
      - ch20/index.qmd
  appendices:
      - ch99/index.qmd
      - contribution.qmd
      - references.qmd

bibliography: refs.bib

format:
  html:
    theme:
      light: [default]
    page-layout: full
    fontsize: "15px"
    linestretch: 1.6
    smooth-scroll: true
    toc-depth: 3
    code-link: true
    code-tools:
      toggle: true
    code-fold: false
    highlight-style: printing
    code-block-bg: true
    code-overflow: wrap
    reference-location: margin
    mermaid:
      theme: neutral

  # see https://pandoc.org/MANUAL.html for all options
  pdf:
    documentclass: style/krantz
    classoption: krantz2
    lof: false
    lot: false
    toc: false
    toc-depth: 2
    fig-cap-location: bottom
    tbl-cap-location: top
    urlcolor: "blue"
    linkcolor: "black"
    biblio-style: apalike
    keep-tex: true
    code-block-bg: "#f2f2f2"
    code-block-border-left: "#f2f2f2"
    code-overflow: wrap
    mermaid:
      theme: neutral
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex

knitr:
  opts_chunk:
    cache: false
    dpi: 100
    fig.width: 8
    fig.height: 5
    out.width: "100%"
    split: true
    R.options:
      animint2.chromote_sleep_seconds: 3
      datatable.print.nrows: 5
      datatable.print.topn: 2
      datatable.print.class: false
      datatable.print.keys: false
      datatable.print.trunc.cols: false
